### ISSUE TITLE
Travis uses Trusty not Xenial for most builds

### ISSUE THREAD

**Issue by hugovk** [etingof/pyasn1#142]
Hi, I don't know if this is really a problem, but I saw it on one of my repos recently so thought I'd mention it here too.

.travis.yml has this:
```yml
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: false
    python: '2.6'
  - os: linux
    dist: xenial
    sudo: false
    python: '2.7'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.2'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.3'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.4'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.5'
  - os: linux
    dist: xenial
    sudo: false
    python: '3.6'
  - os: linux
    dist: xenial
    sudo: true
    python: '3.7'
  - os: linux
    dist: xenial
    sudo: true
    python: 'nightly'
  - os: linux
    dist: xenial
    sudo: false
    python: 'pypy'
  - os: linux
    dist: xenial
    sudo: false
    python: 'pypy3'
```

However, despite `dist: xenial`, all but `3.7` and `nightly` are defaulting back to Trusty as Xenial is not (yet?) available for those.

For example, the "Build system information" for `2.7` shows Xenial was requested, but Trusty was used:

```
Build language: python
Build group: stable
Build dist: xenial
Build id: 415626166
Job id: 415626168
Runtime kernel version: 4.14.12-041412-generic
travis-build version: afa768cd5
Build image provisioning date and time
Tue Dec  5 20:11:19 UTC 2017
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

https://travis-ci.org/etingof/pyasn1/jobs/415626168#L20
